Gemfile.lock
app/views/pages/home.html.erb
app/views/pages/index.html.erb
app/views/pages/show.html.erb

home and index pages created only

---

app/controllers/decks_controller.rb
test/controllers/decks_controller_test.rb

controller done

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_level_card.scss
app/views/decks/index.html.erb

basic index page layout, plus locked icons

---

app/views/decks/show.html.erb

read the title of my pull request

START or NEXT button added on show page

---

app/assets/stylesheets/components/_level_card.scss
app/controllers/decks_controller.rb
app/views/decks/index.html.erb
app/views/decks/levels.html.erb
app/views/pages/home.html.erb
config/routes.rb

created views for: levels-index, and sub-index

---

db/seeds.rb

Updated with more seeds
5 more questions on intermediate and Advanced

 seeds updated

---

db/seeds.rb

Updated all team members with avatar photo
do rails db:seed and rails db:migrate

Avatar all

---

app/javascript/controllers/start_button_controller.js
app/views/decks/show.html.erb

New file : 
javascript/controllers/start_button_controller.js
Still in the works will try to finish tonight

started stimulus for start button

---

app/assets/stylesheets/components/_level_card.scss
app/assets/stylesheets/pages/_home.scss
app/views/decks/index.html.erb
app/views/decks/levels.html.erb
app/views/pages/home.html.erb

The front end for levels Index is basically less done. Minus David's Navbar.

Levels index done (except Navbar)

---

app/assets/stylesheets/components/_level_card.scss
app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

Finished navbar buttons and colors

Index show

---

app/assets/stylesheets/components/_progress_bar_levels.scss
app/views/decks/_progress_bar_levels.html.erb
app/views/decks/levels.html.erb

For now it's on the levels page. There will be 3 different progress bars (for entire game, individual level, individual deck).

Progress bar v1

---

app/assets/stylesheets/components/_level_card.scss
app/assets/stylesheets/pages/_home.scss
app/views/decks/index.html.erb
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb

"Navbar styling, homepage animation, index pages styling"

Navbar styling, homepage animation, index pages styling

---

app/assets/stylesheets/components/_level_card.scss
app/controllers/decks_controller.rb
app/views/decks/index.html.erb
app/views/decks/questions.json.jbuilder
config/routes.rb

"DB and backend processes for questions"  Should line up with Kitty's JS

DB and backend processes for questions

---

app/controllers/decks_controller.rb
app/views/decks/menu.html.erb
app/views/shared/_navbar.html.erb
config/routes.rb

Menu options completed

---

app/views/decks/levels.html.erb

:progressbar removed

---

app/javascript/controllers/game_controller.js
app/views/decks/_question_and_answers_template.html.erb
app/views/decks/show.html.erb

Deck selected is now connected to questions

Fetch javascript

---

app/views/shared/_navbar.html.erb

added link ruby doc to ? when on show page

added link ruby doc to ?

---

app/assets/stylesheets/components/_level_card.scss
app/assets/stylesheets/pages/_home.scss
app/views/decks/show.html.erb
db/seeds.rb

seeds for questions

---

app/controllers/application_controller.rb
app/helpers/meta_tags_helper.rb
app/views/decks/show.html.erb
app/views/layouts/application.html.erb
config/initializers/default_meta.rb
config/meta.yml
public/404.html

Hi I found a customized 404 error page on Codepen.io.
I am waiting for your approval to see if you like it!

404 error page

---

app/views/shared/_navbar.html.erb

removed return on the menu

---

app/assets/stylesheets/components/_show.scss
app/javascript/controllers/game_controller.js
app/views/decks/_question_and_answers_template.html.erb
app/views/decks/show.html.erb

bugs at question page are fixed now

Showpage frontend final

---

app/views/shared/_navbar.html.erb

Fixed menu button .
Now returns to the previous page if you already on the menu page

fixed menu button

---

app/assets/stylesheets/components/_show.scss
app/views/decks/_question_and_answers_template.html.erb

answer buttons now are stylized

Showpage buttons

---

app/assets/stylesheets/components/_progress_bar_levels.scss
app/javascript/controllers/game_controller.js
app/views/decks/_progress_bar_levels.html.erb
app/views/decks/_stopwatch.html.erb
app/views/decks/show.html.erb
app/views/decks/stopwatch.html.erb
config/routes.rb

Basic timer set up
Starts after the tips and freezes once reached the congratulations page

Timer clock

---

app/assets/stylesheets/components/_level_card.scss
app/assets/stylesheets/components/_navbar.scss

Made border thicker. Decreased height so that we can include the new Multiplayer button

Levels buttons border

---

app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

Removed the border radius on the yellow tips box

Tips box styling

---

app/models/concerns/level.rb
app/models/racetrack.rb
app/models/user.rb
app/views/decks/index.html.erb
app/views/decks/levels.html.erb
db/migrate/20230905143328_create_racetracks.rb
db/schema.rb
db/seeds.rb
test/models/racetrack_test.rb

Multiplayer button on levels, decks on decks index, and questions on showpage are complete.

Multiplayer

---

app/assets/stylesheets/pages/_home.scss

Fixed border of start button. Also made it responsive to bigger screen.

Fixed border of start button. Also made it responsive to bigger screen

---

db/seeds.rb

There was a seed that had question_3 instead of question_13

Modify seeds

---

app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

Added profile photo and username name on the menu page

Animations

---

app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb
db/seeds.rb

Styled a basic photo and name inside the account of a user, on the menu page

Username styling

---

app/assets/stylesheets/pages/_home.scss

These buttons are resized properly: Start, Log in, Signup

These buttons are resized properly: Start, Log in, Signup

---

app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

Finally made the box of the button clickable. The spacing between the log in and sign up button is decent too.

Start button remove disappear

---

app/views/shared/_navbar.html.erb

Back button is now fixed
It should return always to the previous page

back button fixed

---

app/assets/stylesheets/components/_congratulations.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_home.scss
app/javascript/controllers/game_controller.js
app/views/decks/_progress_bar_levels.html.erb
app/views/decks/index.html.erb
app/views/shared/_navbar.html.erb

Fixing bugs

---

app/javascript/controllers/game_controller.js

Disable answers

---

public/404.html
public/422.html
public/500.html

added homepage links to both pages

Error pages link homepage

---

app/views/layouts/application.html.erb

fixed sizes of image according to demo checklist

---

app/assets/stylesheets/components/_navbar.scss
app/javascript/controllers/game_controller.js
app/views/decks/_menu.html.erb
app/views/shared/_navbar.html.erb

New tips and menu pages are done

Tips and menu

---

app/views/decks/index.html.erb

I fixed the locked decks  ---> now disabled.
Now in each levels the first deck is unlocked but we will lock the levels anyway so it doesn't matter.

disabled locked decks

---

app/views/decks/levels.html.erb

Managed to disable the locked levels

disabled the locked levels

---

app/controllers/racetracks_controller.rb
app/views/decks/levels.html.erb
app/views/racetracks/index.html.erb
config/routes.rb

history pages and racetrack pages ready (unstyled)

---

app/assets/stylesheets/components/_level_card.scss

When you click on the locked levels it becomes red

locked levels become red

---

app/assets/stylesheets/components/_progress_bar_levels.scss
app/assets/stylesheets/components/_show.scss
app/views/decks/_progress_bar_levels.html.erb
app/views/decks/_progress_bar_multiplayer.html.erb
app/views/decks/show.html.erb

Adjusted question cards dimensions for all decks including the multiplayer question cards because we have the goal of ensuring that the rival user's progress bar remains at the same place all throughout the game

Multiplayer styling card progress

---

app/views/decks/levels.html.erb

Multiplayer pop-up menu now fully linked

---

app/views/decks/_progress_bar_levels.html.erb
app/views/decks/_progress_bar_multiplayer.html.erb

Fixed multiplayer
It displays  loser and winner page

Progbar fix2

---

app/assets/stylesheets/components/_progress_bar_levels.scss
app/views/decks/_progress_bar_levels.html.erb
app/views/decks/_progress_bar_multiplayer.html.erb

Fixed progress bar styling and multiplayer

Opp green bar

---

app/javascript/controllers/game_controller.js
db/seeds.rb

Updated new avatar photos for each user
Don't forget to do rails db:seed

uploaded new avatar photos for each user

---

db/seeds.rb

Made the first two decks completed in the beginner level.

Seeds demo day

---

db/seeds.rb

new grant photo

---

app/assets/stylesheets/components/_join_race.scss
app/assets/stylesheets/pages/_history.scss
app/assets/stylesheets/pages/_index.scss
app/views/decks/levels.html.erb
app/views/racetracks/history.html.erb
app/views/racetracks/index.html.erb

Open races

---

app/assets/stylesheets/components/_history.scss
app/assets/stylesheets/components/_show.scss
app/javascript/controllers/game_controller.js
app/views/decks/_question_and_answers_template.html.erb

Wrong and correct answers now have colors

Buttons color fixed

---

app/views/racetracks/history.html.erb
app/views/racetracks/index.html.erb

fixed the select a race title because it was previously just plain text. Changed naming of titles to make it concise.

Edit titles in racetracks

---

app/assets/stylesheets/components/_avatar.scss
app/views/racetracks/history.html.erb

Avatar height changed, history page updated

clarified info displayed on history

---

app/views/racetracks/history.html.erb

WIN displays green LOSS displays red

history page text decoration
